# Generated by Django 4.1.1 on 2022-09-15 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200, verbose_name='عنوان وصول الطلبية')),
                ('apartment_address', models.CharField(max_length=100, verbose_name='عنوان الشقة')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='الدولة')),
                ('city', models.CharField(max_length=40, verbose_name='المدينة')),
                ('phone', models.CharField(max_length=10, verbose_name='رقم الهاتف')),
                ('save_info', models.BooleanField(default=False, verbose_name='احفظ هذه المعلومات في المرة القادمة')),
                ('gps', models.CharField(max_length=20, verbose_name='موقع احداثيات الطلب')),
                ('default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='اسم حساب الزبون')),
            ],
            options={
                'verbose_name': 'تفاصيل تسليم الطلبية',
                'verbose_name_plural': 'صفحة بيانات وتفاصيل تسليم الطلبية',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(verbose_name='رمز التصنيف')),
                ('description', models.TextField(verbose_name='وصف التصنيف')),
                ('image', models.ImageField(upload_to='', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مجموعة الاصناف',
                'verbose_name_plural': 'صفحة التصنيفات واقسام الموقع',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الصنف')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='السعر بعد التخفيض')),
                ('label', models.CharField(choices=[('S', 'للبيع'), ('N', 'جديد'), ('P', 'الكمية محدودة')], default='S', max_length=1, verbose_name='شعار')),
                ('slug', models.SlugField(verbose_name='رمز الصنف')),
                ('stock_no', models.CharField(max_length=10, verbose_name='الكمية المتوفرة')),
                ('description_short', models.CharField(max_length=50, verbose_name='وصف الصنف')),
                ('description_long', models.TextField(verbose_name='تفاصيل الصنف')),
                ('image', models.ImageField(upload_to='', verbose_name='صورة الصنف')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة جانبية للصنف')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة جانبية 2 للصنف')),
                ('title_right', models.CharField(blank=True, max_length=100, null=True, verbose_name='تفاصيل اكثر')),
                ('title_left', models.CharField(blank=True, max_length=100, null=True, verbose_name='معلومات اخرى')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'صفحة اضافة الاصناف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=20, verbose_name='رقم الكود')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('ordered_date', models.DateTimeField(verbose_name='تاريخ الطلب')),
                ('ordered', models.BooleanField(default=False, verbose_name='تم توفير الطلب')),
                ('being_delivered', models.BooleanField(default=False, verbose_name='يتم تسليم الطلب')),
                ('received', models.BooleanField(default=False, verbose_name='تم ايصال الطلب')),
                ('refund_requested', models.BooleanField(default=False, verbose_name='استرداد الطلب')),
                ('refund_granted', models.BooleanField(default=False, verbose_name='منح صلاحية امكانية استرجاع الطلب')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='billing_address', to='core.billingaddress', verbose_name='عنوان الزبون لدفع الفاتورة')),
            ],
            options={
                'verbose_name': 'الطلبيات',
                'verbose_name_plural': 'صفحة عرض الطلبيات التي تم تسجيلها ',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(max_length=100, verbose_name='عنوان الصورة')),
                ('caption2', models.CharField(max_length=100, verbose_name='التعليق على الصورة')),
                ('link', models.CharField(max_length=100, verbose_name='صفحة الارتباط')),
                ('image', models.ImageField(help_text='Size: 1920x570', upload_to='', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'خلفيات دعائية',
                'verbose_name_plural': 'صفحة اضافة صور خلفيات دعائية عن الموقع ومحتوياتة',
            },
        ),
        migrations.CreateModel(
            name='sizeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='حجم ومقاس الصنف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'احجام ومقاسات الاصناف',
                'verbose_name_plural': 'صفحة اضافة احجام ومقاسات الاصناف',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('accepted', models.BooleanField(default=False, verbose_name='الموافقة')),
                ('email', models.EmailField(max_length=254, verbose_name='عنوان البريد الالكتروني')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'الطلبيات المرفوظة',
                'verbose_name_plural': 'صفحة عرض الطلبيات المرفوظة',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='تم الطلب')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية المطلوبة')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تاكيد الطلب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.item', verbose_name='الصنف')),
                ('sizeItem', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.sizeitems', verbose_name='حجم ومقاس الصنف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='اسم حساب الزبون')),
            ],
            options={
                'verbose_name': 'طلبيات الزبائن',
                'verbose_name_plural': 'صفحة عرض طلبيات الزبائن ',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.orderitem', verbose_name='الصنف'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shipping_address', to='core.billingaddress', verbose_name='عنوان الزبون لتوصيل الطلبية'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='اسم حساب الزبون'),
        ),
    ]
