# Generated by Django 4.1.1 on 2022-09-17 17:13

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='gps',
            field=location_field.models.plain.PlainLocationField(max_length=63, verbose_name='موقع احداثيات الطلب'),
        ),
    ]
