# Generated by Django 4.1.1 on 2022-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_billingaddress_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='gps',
            field=models.CharField(max_length=20, verbose_name='موقع احداثيات الطلب'),
        ),
    ]
