# Generated by Django 4.1.1 on 2022-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_sizeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeitems',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='الافتراضي'),
        ),
    ]
