# Generated by Django 4.1.1 on 2022-09-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sizeitems_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeitems',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='الافتراضي'),
        ),
    ]
